---
- hosts: api1
  gather_facts: no
  tasks:
    - name: 获取Ceph状态
      register: ceph_status
      shell: ceph -s | grep health | awk '{print $2}'

    - fail: msg = "Ceph状态异常"
      when: ceph_status.stdout != "HEALTH_OK"
