---
- hosts: api1
  gather_facts: no
  tasks:
    - name: 拷贝创建虚拟机脚本
      copy: 
        src: ./test-boot-vm.sh 
        dest: /tmp/test-boot-vm.sh
        owner: root
        group: root
        mode: 0755
    - name: 测试能否创建虚拟机
      command: /tmp/test-boot-vm.sh
